// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5Jit0sCzHaQ2s1RU9kF5bH0sQMPf95A',
    appId: '1:986133920681:web:f2ecebd4feaeacb86aa2b8',
    messagingSenderId: '986133920681',
    projectId: 'gdsc-hacks',
    authDomain: 'gdsc-hacks.firebaseapp.com',
    databaseURL: 'https://gdsc-hacks-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-hacks.appspot.com',
    measurementId: 'G-5E66ZRG42H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJIUQjTkl-lUIZuDXaVR7YdUIkK1Txo0',
    appId: '1:986133920681:android:13d43eb56a992d566aa2b8',
    messagingSenderId: '986133920681',
    projectId: 'gdsc-hacks',
    databaseURL: 'https://gdsc-hacks-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-hacks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFiUDvexOYzgeD8YULP2I7X0UJel4ShxE',
    appId: '1:986133920681:ios:d76be0c5d11a6b0c6aa2b8',
    messagingSenderId: '986133920681',
    projectId: 'gdsc-hacks',
    databaseURL: 'https://gdsc-hacks-default-rtdb.firebaseio.com',
    storageBucket: 'gdsc-hacks.appspot.com',
    iosClientId: '986133920681-m1jrcoaqbo7mnh73afkee85a43i1q2pm.apps.googleusercontent.com',
    iosBundleId: 'com.team.b',
  );
}
